// Generated API configuration (mirrors core/config.go).

#include "api.h"

#include <string.h>

voxgig_value* make_config(void) {
  return cmap(4,
    "main", cmap(4,
      "name", v_str("Linear"),
      "slug", v_str("linear"),
      "version", v_str("0.0.1"),
      "target", v_str("c")),
    "feature", cmap(8,
      "debug", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "max", v_num(100),
          "redact", clist(7,
            v_str("authorization"),
            v_str("cookie"),
            v_str("set-cookie"),
            v_str("api-key"),
            v_str("apikey"),
            v_str("x-api-key"),
            v_str("idempotency-key"))),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "onEntry", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "idempotency", cmap(4,
        "options", cmap(4,
          "active", v_bool(false),
          "header", v_str("Idempotency-Key"),
          "methods", clist(4,
            v_str("POST"),
            v_str("PUT"),
            v_str("PATCH"),
            v_str("DELETE")),
          "ops", clist(3,
            v_str("create"),
            v_str("update"),
            v_str("remove"))),
        "optspec", cmap(1,
          "keygen", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "metrics", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(1,
          "now", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "paging", cmap(4,
        "options", cmap(7,
          "active", v_bool(false),
          "afterVar", v_str("after"),
          "cursorParam", v_str("cursor"),
          "firstVar", v_str("first"),
          "limitParam", v_str("limit"),
          "pageParam", v_str("page"),
          "startPage", v_num(1)),
        "optspec", cmap(2,
          "limit", v_str("`$NUMBER`"),
          "ops", v_str("`$LIST`")),
        "strict", v_bool(false),
        "transport", v_str("none")),
      "ratelimit", cmap(4,
        "options", cmap(3,
          "active", v_bool(false),
          "burst", v_num(5),
          "rate", v_num(5)),
        "optspec", cmap(2,
          "now", v_str("`$FUNCTION`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "retry", cmap(4,
        "options", cmap(6,
          "active", v_bool(false),
          "factor", v_num(2),
          "maxDelay", v_num(2000),
          "minDelay", v_num(50),
          "retries", v_num(2),
          "statuses", clist(7,
            v_num(408),
            v_num(425),
            v_num(429),
            v_num(500),
            v_num(502),
            v_num(503),
            v_num(504))),
        "optspec", cmap(2,
          "jitter", v_str("`$BOOLEAN`"),
          "sleep", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap")),
      "test", cmap(4,
        "options", cmap(1,
          "active", v_bool(false)),
        "optspec", cmap(2,
          "entity", v_str("`$MAP`"),
          "net", v_str("`$MAP`")),
        "strict", v_bool(false),
        "transport", v_str("base")),
      "timeout", cmap(4,
        "options", cmap(2,
          "active", v_bool(false),
          "ms", v_num(30000)),
        "optspec", cmap(2,
          "clearTimer", v_str("`$FUNCTION`"),
          "setTimer", v_str("`$FUNCTION`")),
        "strict", v_bool(false),
        "transport", v_str("wrap"))),
    "options", cmap(4,
      "base", v_str("https://api.linear.app/graphql"),
      "headers", cmap(1,
        "content-type", v_str("application/json")),
      "entity", cmap(2,
        "issue", v_map(),
        "team", v_map()),
      "auth", cmap(1,
        "prefix", v_str(""))),
    "entity", cmap(2,
      "issue", cmap(5,
        "fields", clist(19,
          cmap(2,
            "name", v_str("archivedAt"),
            "type", v_str("`$ANY`")),
          cmap(2,
            "name", v_str("assignee"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("branchName"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("canceledAt"),
            "type", v_str("`$ANY`")),
          cmap(2,
            "name", v_str("completedAt"),
            "type", v_str("`$ANY`")),
          cmap(3,
            "name", v_str("createdAt"),
            "req", v_bool(true),
            "type", v_str("`$ANY`")),
          cmap(2,
            "name", v_str("creator"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("description"),
            "type", v_str("`$STRING`")),
          cmap(2,
            "name", v_str("dueDate"),
            "type", v_str("`$ANY`")),
          cmap(2,
            "name", v_str("estimate"),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("identifier"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("number"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`")),
          cmap(3,
            "name", v_str("priority"),
            "req", v_bool(true),
            "type", v_str("`$NUMBER`")),
          cmap(2,
            "name", v_str("state"),
            "type", v_str("`$OBJECT`")),
          cmap(2,
            "name", v_str("team"),
            "type", v_str("`$OBJECT`")),
          cmap(3,
            "name", v_str("title"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("updatedAt"),
            "req", v_bool(true),
            "type", v_str("`$ANY`")),
          cmap(3,
            "name", v_str("url"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("issue"),
        "op", cmap(4,
          "create", cmap(3,
            "input", v_str("data"),
            "name", v_str("create"),
            "points", clist(1,
              cmap(9,
                "args", v_map(),
                "graphql", cmap(4,
                  "doc", v_str("mutation IssueCreate($input: IssueCreateInput!) { issueCreate(input: $input) { issue { ...IssueFields } success } } fragment IssueFields on Issue { archivedAt assignee { id } branchName canceledAt completedAt createdAt creator { id } description dueDate estimate id identifier number priority state { id } team { id } title updatedAt url }"),
                  "field", v_str("issueCreate"),
                  "optype", v_str("mutation"),
                  "vars", clist(1,
                    cmap(3,
                      "from", v_str(""),
                      "gqltype", v_str("IssueCreateInput!"),
                      "name", v_str("input")))),
                "kind", v_str("graphql"),
                "method", v_str("POST"),
                "orig", v_str("issueCreate"),
                "segments", v_list(),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data.issueCreate.issue`")),
                "parts", v_list()))),
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(4,
                      "kind", v_str("param"),
                      "name", v_str("after"),
                      "orig", v_str("after"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("param"),
                      "name", v_str("first"),
                      "orig", v_str("first"),
                      "type", v_str("`$INTEGER`")))),
                "graphql", cmap(5,
                  "doc", v_str("query IssueList($first: Int, $after: String) { issues(first: $first, after: $after) { edges { node { ...IssueFields } } pageInfo { endCursor hasNextPage } } } fragment IssueFields on Issue { archivedAt assignee { id } branchName canceledAt completedAt createdAt creator { id } description dueDate estimate id identifier number priority state { id } team { id } title updatedAt url }"),
                  "field", v_str("issues"),
                  "optype", v_str("query"),
                  "page", cmap(4,
                    "cursor", v_str("pageInfo.endCursor"),
                    "more", v_str("pageInfo.hasNextPage"),
                    "nodes", v_str("edges"),
                    "style", v_str("relay")),
                  "vars", clist(2,
                    cmap(3,
                      "from", v_str("first"),
                      "gqltype", v_str("Int"),
                      "name", v_str("first")),
                    cmap(3,
                      "from", v_str("after"),
                      "gqltype", v_str("String"),
                      "name", v_str("after")))),
                "kind", v_str("graphql"),
                "method", v_str("POST"),
                "orig", v_str("issues"),
                "segments", v_list(),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data.issues.edges`")),
                "parts", v_list()))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "graphql", cmap(4,
                  "doc", v_str("query IssueLoad($id: String!) { issue(id: $id) { ...IssueFields } } fragment IssueFields on Issue { archivedAt assignee { id } branchName canceledAt completedAt createdAt creator { id } description dueDate estimate id identifier number priority state { id } team { id } title updatedAt url }"),
                  "field", v_str("issue"),
                  "optype", v_str("query"),
                  "vars", clist(1,
                    cmap(3,
                      "from", v_str("id"),
                      "gqltype", v_str("String!"),
                      "name", v_str("id")))),
                "kind", v_str("graphql"),
                "method", v_str("POST"),
                "orig", v_str("issue"),
                "segments", v_list(),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data.issue`")),
                "parts", v_list()))),
          "update", cmap(3,
            "input", v_str("data"),
            "name", v_str("update"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "graphql", cmap(4,
                  "doc", v_str("mutation IssueUpdate($id: String!, $input: IssueUpdateInput!) { issueUpdate(id: $id, input: $input) { issue { ...IssueFields } success } } fragment IssueFields on Issue { archivedAt assignee { id } branchName canceledAt completedAt createdAt creator { id } description dueDate estimate id identifier number priority state { id } team { id } title updatedAt url }"),
                  "field", v_str("issueUpdate"),
                  "optype", v_str("mutation"),
                  "vars", clist(2,
                    cmap(3,
                      "from", v_str("id"),
                      "gqltype", v_str("String!"),
                      "name", v_str("id")),
                    cmap(3,
                      "from", v_str(""),
                      "gqltype", v_str("IssueUpdateInput!"),
                      "name", v_str("input")))),
                "kind", v_str("graphql"),
                "method", v_str("POST"),
                "orig", v_str("issueUpdate"),
                "segments", v_list(),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data.issueUpdate.issue`")),
                "parts", v_list())))),
        "relations", cmap(1,
          "ancestors", v_list())),
      "team", cmap(5,
        "fields", clist(4,
          cmap(2,
            "name", v_str("description"),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("id"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("key"),
            "req", v_bool(true),
            "type", v_str("`$STRING`")),
          cmap(3,
            "name", v_str("name"),
            "req", v_bool(true),
            "type", v_str("`$STRING`"))),
        "id", cmap(2,
          "field", v_str("id"),
          "name", v_str("id")),
        "name", v_str("team"),
        "op", cmap(2,
          "list", cmap(3,
            "input", v_str("data"),
            "name", v_str("list"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(2,
                    cmap(4,
                      "kind", v_str("param"),
                      "name", v_str("after"),
                      "orig", v_str("after"),
                      "type", v_str("`$STRING`")),
                    cmap(4,
                      "kind", v_str("param"),
                      "name", v_str("first"),
                      "orig", v_str("first"),
                      "type", v_str("`$INTEGER`")))),
                "graphql", cmap(4,
                  "doc", v_str("query TeamList($first: Int, $after: String) { teams(first: $first, after: $after) { ...TeamFields } } fragment TeamFields on Team { description id key name }"),
                  "field", v_str("teams"),
                  "optype", v_str("query"),
                  "vars", clist(2,
                    cmap(3,
                      "from", v_str("first"),
                      "gqltype", v_str("Int"),
                      "name", v_str("first")),
                    cmap(3,
                      "from", v_str("after"),
                      "gqltype", v_str("String"),
                      "name", v_str("after")))),
                "kind", v_str("graphql"),
                "method", v_str("POST"),
                "orig", v_str("teams"),
                "segments", v_list(),
                "select", v_map(),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data.teams`")),
                "parts", v_list()))),
          "load", cmap(3,
            "input", v_str("data"),
            "name", v_str("load"),
            "points", clist(1,
              cmap(9,
                "args", cmap(1,
                  "params", clist(1,
                    cmap(5,
                      "kind", v_str("param"),
                      "name", v_str("id"),
                      "orig", v_str("id"),
                      "reqd", v_bool(true),
                      "type", v_str("`$STRING`")))),
                "graphql", cmap(4,
                  "doc", v_str("query TeamLoad($id: String!) { team(id: $id) { ...TeamFields } } fragment TeamFields on Team { description id key name }"),
                  "field", v_str("team"),
                  "optype", v_str("query"),
                  "vars", clist(1,
                    cmap(3,
                      "from", v_str("id"),
                      "gqltype", v_str("String!"),
                      "name", v_str("id")))),
                "kind", v_str("graphql"),
                "method", v_str("POST"),
                "orig", v_str("team"),
                "segments", v_list(),
                "select", cmap(1,
                  "exist", clist(1,
                    v_str("id"))),
                "transform", cmap(2,
                  "req", v_str("`reqdata`"),
                  "res", v_str("`body.data.team`")),
                "parts", v_list())))),
        "relations", cmap(1,
          "ancestors", v_list()))));
}

// SHARED CONFIG (sdkgen rung L2).
//
// The SDK reads the config on every request and never writes to it, so one
// instance is shared by every client rather than rebuilt per client. Above the
// size threshold make_config re-parses the whole embedded JSON, so this is the
// difference between parsing the model once and once per client.
//
// Deliberately never freed: it lives for the life of the process, like any
// other program-lifetime singleton.
static voxgig_value* shared_config_val = NULL;

// The process-wide config, built once on first use.
//
// The returned value is SHARED: treat it as read-only. Callers that need to
// mutate should use make_config, which always returns a fresh copy.
voxgig_value* shared_config(void) {
  if (NULL == shared_config_val) {
    shared_config_val = make_config();
  }
  return shared_config_val;
}

Feature* feature_debug_new(void);
Feature* feature_idempotency_new(void);
Feature* feature_metrics_new(void);
Feature* feature_paging_new(void);
Feature* feature_ratelimit_new(void);
Feature* feature_retry_new(void);
Feature* feature_test_new(void);
Feature* feature_timeout_new(void);

Feature* make_feature(const char* name) {
  if (strcmp(name, "debug") == 0) return feature_debug_new();
  if (strcmp(name, "idempotency") == 0) return feature_idempotency_new();
  if (strcmp(name, "metrics") == 0) return feature_metrics_new();
  if (strcmp(name, "paging") == 0) return feature_paging_new();
  if (strcmp(name, "ratelimit") == 0) return feature_ratelimit_new();
  if (strcmp(name, "retry") == 0) return feature_retry_new();
  if (strcmp(name, "test") == 0) return feature_test_new();
  if (strcmp(name, "timeout") == 0) return feature_timeout_new();
  return feature_base_new();
}


void** feature_plugins(const char* name, size_t* n) {
  (void)name;
  *n = 0;
  return NULL;
}
