// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/linear-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.LinearSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.LinearSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.LinearSDK, name string) (sdk.LinearEntity, error) {
	switch strings.ToLower(name) {
	case "access_key_release":
		return client.AccessKeyRelease(nil), nil
	case "access_key_release_pipeline":
		return client.AccessKeyReleasePipeline(nil), nil
	case "agent_activity":
		return client.AgentActivity(nil), nil
	case "agent_session":
		return client.AgentSession(nil), nil
	case "agent_skill":
		return client.AgentSkill(nil), nil
	case "application":
		return client.Application(nil), nil
	case "attachment":
		return client.Attachment(nil), nil
	case "audit_entry":
		return client.AuditEntry(nil), nil
	case "audit_entry_type":
		return client.AuditEntryType(nil), nil
	case "auth_resolver_response":
		return client.AuthResolverResponse(nil), nil
	case "authentication_session_response":
		return client.AuthenticationSessionResponse(nil), nil
	case "comment":
		return client.Comment(nil), nil
	case "create_or_join_organization_response":
		return client.CreateOrJoinOrganizationResponse(nil), nil
	case "custom_view":
		return client.CustomView(nil), nil
	case "customer":
		return client.Customer(nil), nil
	case "customer_need":
		return client.CustomerNeed(nil), nil
	case "customer_status":
		return client.CustomerStatus(nil), nil
	case "customer_tier":
		return client.CustomerTier(nil), nil
	case "cycle":
		return client.Cycle(nil), nil
	case "diff":
		return client.Diff(nil), nil
	case "document":
		return client.Document(nil), nil
	case "document_search_result":
		return client.DocumentSearchResult(nil), nil
	case "email_intake_address":
		return client.EmailIntakeAddress(nil), nil
	case "email_user_account_auth_challenge_response":
		return client.EmailUserAccountAuthChallengeResponse(nil), nil
	case "emoji":
		return client.Emoji(nil), nil
	case "entity_external_link":
		return client.EntityExternalLink(nil), nil
	case "external_user":
		return client.ExternalUser(nil), nil
	case "favorite":
		return client.Favorite(nil), nil
	case "git_automation_state":
		return client.GitAutomationState(nil), nil
	case "git_automation_target_branch":
		return client.GitAutomationTargetBranch(nil), nil
	case "git_hub_integration_connect_detail":
		return client.GitHubIntegrationConnectDetail(nil), nil
	case "initiative":
		return client.Initiative(nil), nil
	case "initiative_label":
		return client.InitiativeLabel(nil), nil
	case "initiative_lead_team_change_impact":
		return client.InitiativeLeadTeamChangeImpact(nil), nil
	case "initiative_relation":
		return client.InitiativeRelation(nil), nil
	case "initiative_to_project":
		return client.InitiativeToProject(nil), nil
	case "initiative_update":
		return client.InitiativeUpdate(nil), nil
	case "integration":
		return client.Integration(nil), nil
	case "integration_template":
		return client.IntegrationTemplate(nil), nil
	case "integrations_setting":
		return client.IntegrationsSetting(nil), nil
	case "issue":
		return client.Issue(nil), nil
	case "issue_import":
		return client.IssueImport(nil), nil
	case "issue_label":
		return client.IssueLabel(nil), nil
	case "issue_priority_value":
		return client.IssuePriorityValue(nil), nil
	case "issue_relation":
		return client.IssueRelation(nil), nil
	case "issue_search_result":
		return client.IssueSearchResult(nil), nil
	case "issue_to_release":
		return client.IssueToRelease(nil), nil
	case "logout_response":
		return client.LogoutResponse(nil), nil
	case "notification":
		return client.Notification(nil), nil
	case "notification_subscription":
		return client.NotificationSubscription(nil), nil
	case "o_auth_application":
		return client.OAuthApplication(nil), nil
	case "organization":
		return client.Organization(nil), nil
	case "organization_domain":
		return client.OrganizationDomain(nil), nil
	case "organization_invite":
		return client.OrganizationInvite(nil), nil
	case "organization_meta":
		return client.OrganizationMeta(nil), nil
	case "passkey_login_start_response":
		return client.PasskeyLoginStartResponse(nil), nil
	case "project":
		return client.Project(nil), nil
	case "project_label":
		return client.ProjectLabel(nil), nil
	case "project_milestone":
		return client.ProjectMilestone(nil), nil
	case "project_milestone_move_project_team":
		return client.ProjectMilestoneMoveProjectTeam(nil), nil
	case "project_relation":
		return client.ProjectRelation(nil), nil
	case "project_search_result":
		return client.ProjectSearchResult(nil), nil
	case "project_status":
		return client.ProjectStatus(nil), nil
	case "project_update":
		return client.ProjectUpdate(nil), nil
	case "push_subscription":
		return client.PushSubscription(nil), nil
	case "reaction":
		return client.Reaction(nil), nil
	case "release":
		return client.Release(nil), nil
	case "release_note":
		return client.ReleaseNote(nil), nil
	case "release_pipeline":
		return client.ReleasePipeline(nil), nil
	case "release_stage":
		return client.ReleaseStage(nil), nil
	case "roadmap":
		return client.Roadmap(nil), nil
	case "roadmap_to_project":
		return client.RoadmapToProject(nil), nil
	case "sla_configuration":
		return client.SlaConfiguration(nil), nil
	case "sso_url_from_email_response":
		return client.SsoUrlFromEmailResponse(nil), nil
	case "team":
		return client.Team(nil), nil
	case "team_membership":
		return client.TeamMembership(nil), nil
	case "template":
		return client.Template(nil), nil
	case "time_schedule":
		return client.TimeSchedule(nil), nil
	case "triage_responsibility":
		return client.TriageResponsibility(nil), nil
	case "upload_file":
		return client.UploadFile(nil), nil
	case "usage_alert":
		return client.UsageAlert(nil), nil
	case "user":
		return client.User(nil), nil
	case "user_setting":
		return client.UserSetting(nil), nil
	case "view_preference":
		return client.ViewPreference(nil), nil
	case "webhook":
		return client.Webhook(nil), nil
	case "webhook_failure_event":
		return client.WebhookFailureEvent(nil), nil
	case "workflow_state":
		return client.WorkflowState(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
